
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-25T21:28:54+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "1c9475d5cafdcbe789f8d3c2e3027b92a27c34d4",
 "version": "0.4rc1+4.g1c9475d5.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
