Document: qtpyvcp
Title: Debian qtpyvcp Manual
Author: <insert document author here>
Abstract: This manual describes what qtpyvcp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtpyvcp/qtpyvcp.sgml.gz

Format: postscript
Files: /usr/share/doc/qtpyvcp/qtpyvcp.ps.gz

Format: text
Files: /usr/share/doc/qtpyvcp/qtpyvcp.text.gz

Format: HTML
Index: /usr/share/doc/qtpyvcp/html/index.html
Files: /usr/share/doc/qtpyvcp/html/*.html
