"""Generate the ``tool_data.ngc`` subroutine from the tool database.

Makes every numeric **extras and custom-column** tool value readable from
G-code, subroutines, and MDI as named global parameters, with the
column's machine key as the parameter name (plan §6 Phase 3 follow-up,
Chris 2026-07-06). Three namespaces, each with exact semantics:

    #<_tool_5_groove_width>       every tool, literal tool number in the
                                  name -- set for ALL tools on every call
    #<_current_tool_groove_width> the tool in the spindle (from #5400,
                                  read inside the sub -- no argument)
    #<_tool_groove_width>         the tool picked by the call argument
                                  ([0] also means the loaded tool)

    o<tool_data> call             (enough for #<_tool_<n>_*> and
                                   #<_current_tool_*>)
    o<tool_data> call [7]         (additionally selects tool 7 into
                                   #<_tool_*>)

Core LinuxCNC columns (offsets, diameter, angles, orientation) are
deliberately NOT mirrored here (Chris, 2026-07-06): LinuxCNC already
exposes the loaded tool's core data live (#5400-#5413, G43), a second
copy could silently desync after a mid-run G10/touch-off, and stock
LinuxCNC deliberately offers no access to *other* tools' offsets --
offsets are meant to be applied (M6+G43), not computed against from
copies. Keeping core out means nothing in this file can EVER desync:
extras/custom only change through the GUI, which locks all editing
while a program runs. The tool number itself is included as the lookup
sentinel (it is the key, not mirrored data): #<_tool_number> == 0 after
a call means the selected tool is not in the table.

The selected-tool argument is read from #1, which is REQUIRED to be
passed for the #<_tool_*> namespace to be meaningful: LinuxCNC's
interpreter reuses its block structs without zeroing the o-call params[]
array (init_block() resets param_cnt only), so an unpassed #1 can read
as a stale value from an earlier call. Calling with no argument is safe
for the other two namespaces -- they never look at #1.

Inside a remapped toolchange, note that #5400 (and therefore
#<_current_tool_*>) still holds the OUTGOING tool until the change
completes; the incoming tool is the predefined #<_selected_tool>:

    o<tool_data> call [#<_selected_tool>]   (incoming tool -> #<_tool_*>)

Why a generated subroutine file (and not HAL pins, a toolchange remap,
or MDI pushes): LinuxCNC's interpreter drops its o-word file cache after
every MDI command and at the end of every program run
(``_setup.offset_map.clear()`` in rs274ngc_pre.cc), so a file
regenerated by the GUI is picked up by the very next call -- a custom
column created in the Add Column dialog is readable from G-code seconds
later, no restart, no ini changes. Values are *pulled* at the point of
use (the o-call executes inline in the program), so there is no push
mechanism to go stale.

Text columns (custom text fields; extras like type/insert_shape/holder
codes are text too) are skipped: RS274 has no string type under any
mechanism. They remain available to widgets via getPlugin('tooltable')
and the ``tooltable:current_tool`` Rules channel. Bools become 1/0;
NULL/unset numeric cells become 0 (a named parameter that was never
assigned ERRORS on read in RS274, so every field is always assigned).
"""

SUB_NAME = 'tool_data'
SUB_FILE_NAME = SUB_NAME + '.ngc'

# The tool number is emitted alongside the extras/custom fields as the
# lookup sentinel, so its key is reserved just like the column names.
NUMBER_KEY = 'number'


def _fmt(value):
    """Format a value as an RS274 number literal.

    Fixed-point only: %g-style output can produce exponent notation
    (1e-05), which the RS274 parser does not accept. Nine decimal places
    then strip -- keeps full useful precision without trailing noise.
    """
    if value is None:
        value = 0
    if isinstance(value, bool):
        return '1' if value else '0'
    try:
        value = float(value)
    except (TypeError, ValueError):
        return '0'
    text = '%.9f' % value
    text = text.rstrip('0').rstrip('.')
    return text or '0'


def _field_items(tool_no, extras, custom_values, numeric_extras,
                 numeric_custom):
    """Yield (param_key, value) for every G-code-representable field of
    one tool, in stable order: number sentinel, extras, custom."""
    yield NUMBER_KEY, tool_no
    extras = extras or {}
    for key in numeric_extras:
        yield key, extras.get(key)
    custom_values = custom_values or {}
    for key in numeric_custom:
        yield key, custom_values.get(key)


def generate_tool_data_ngc(tool_nos, extras_by_tool, custom_defs,
                           custom_values_by_tool, numeric_extras):
    """Render the complete tool_data.ngc subroutine text.

    Args:
        tool_nos: iterable of tool numbers (tool 0 excluded by caller).
        extras_by_tool: {tool_no: extras dict or None}
        custom_defs: getCustomFieldDefs() result (name/value_type/...)
        custom_values_by_tool: {tool_no: {name: typed value}}
        numeric_extras: ordered extras column names that hold numbers
            (the caller derives this from the ORM column types so this
            module needs no SQLAlchemy dependency).
    """
    numeric_custom = [d['name'] for d in custom_defs
                      if d['value_type'] in ('float', 'int', 'bool')]
    text_custom = sorted(d['name'] for d in custom_defs
                         if d['value_type'] == 'text')

    tool_nos = sorted(int(t) for t in tool_nos if int(t) != 0)

    per_tool_fields = {
        tool_no: list(_field_items(
            tool_no,
            (extras_by_tool or {}).get(tool_no),
            (custom_values_by_tool or {}).get(tool_no),
            numeric_extras, numeric_custom))
        for tool_no in tool_nos
    }
    zero_fields = list(_field_items(
        0, None, None, numeric_extras, numeric_custom))

    lines = [
        '(AUTO-GENERATED by the qtpyvcp tool database -- DO NOT EDIT)',
        '(Regenerated automatically whenever the tool table changes.)',
        '(Core LinuxCNC values are not mirrored here on purpose --)',
        '(use #5400-#5413 / G43 for the loaded tool, as always.)',
        '(Usage:)',
        '(  o<%s> call         -> #<_tool_<n>_<key>> for every tool,)' % SUB_NAME,
        '(                          #<_current_tool_<key>> = loaded tool)',
        '(  o<%s> call [n]     -> additionally #<_tool_<key>> = tool n)' % SUB_NAME,
        '(                          [0] or [#5400] also mean the loaded tool)',
        '(  #<_tool_number> reads 0 after a call for an unknown tool number.)',
        '(  In a toolchange remap, #5400 is still the OUTGOING tool; use)',
        '(  o<%s> call [#<_selected_tool>] for the incoming one.)' % SUB_NAME,
    ]
    if text_custom:
        lines.append('(Text columns have no G-code representation and are '
                     'not included: %s)' % ', '.join(text_custom))
    lines += [
        'o<%s> sub' % SUB_NAME,
        '',
        '(---- all tools, tool number in the parameter name ----)',
    ]

    for tool_no in tool_nos:
        for key, value in per_tool_fields[tool_no]:
            lines.append('#<_tool_%d_%s> = %s' % (tool_no, key, _fmt(value)))

    def _branch_chain(label, param_prefix, selector):
        chain = []
        keyword = 'if'
        for tool_no in tool_nos:
            chain.append('%s %s [%s EQ %d]' % (label, keyword, selector,
                                               tool_no))
            keyword = 'elseif'
            for key, value in per_tool_fields[tool_no]:
                chain.append('  #<%s%s> = %s' % (param_prefix, key,
                                                 _fmt(value)))
        chain.append('%s %s' % (label, 'else' if tool_nos else 'if [1 EQ 1]'))
        for key, _value in zero_fields:
            chain.append('  #<%s%s> = 0' % (param_prefix, key))
        chain.append('%s endif' % label)
        return chain

    lines += [
        '',
        '(---- the loaded tool: #<_current_tool_<key>>, from #5400 ----)',
    ]
    lines += _branch_chain('o100', '_current_tool_', '#5400')

    lines += [
        '',
        '(---- the selected tool: #<_tool_<key>>, from the argument ----)',
        '#<sel> = #1',
        'o200 if [#<sel> LE 0]',
        '  #<sel> = #5400',
        'o200 endif',
    ]
    lines += _branch_chain('o300', '_tool_', '#<sel>')

    lines += [
        '',
        'o<%s> endsub' % SUB_NAME,
        'M2',
        '',
    ]
    return '\n'.join(lines)
