fpm -s python \
    -d python-pyqt5 \
    -d python-dbus.mainloop.pyqt5 \
    -d python-pyqt5.qtopengl \
    -d python-pyqt5.qsci \
    -d python-pyqt5.qtmultimedia \
    -d gstreamer1.0-plugins-bad \
    -d libqt5multimedia5-plugins \
    -d pyqt5-dev-tools \
    -f \
    -m "Kurt Jacobson" \
    -t deb /home/kurt/dev/cnc/QtPyVCP/setup.py
